"use client"

import { useState, useRef, useEffect } from "react"
import { View, Text, ScrollView, Pressable, Image, TextInput, KeyboardAvoidingView, Platform } from "react-native"
import { SafeAreaProvider } from "react-native-safe-area-context"
import { useRouter } from "expo-router"
import { aiChatAssistant } from "@/constants/aiChatAssistant"

interface Message {
  id: string
  type: "user" | "ai"
  content: string
  timestamp: Date
}

export default function AIChatAssistant() {
  const router = useRouter()
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "1",
      type: "user",
      content: "Explain quantum computing in simple terms",
      timestamp: new Date(),
    },
    {
      id: "2",
      type: "ai",
      content: `As an AI, I don't have real-time access to IMDb's rankings, and my training only goes up until September 2021. However, I can provide you with a list of critically acclaimed movies that were highly rated at that time. Please note that opinions on the "best" movies can vary, and IMDb ratings may change over time. Here are ten highly regarded films as of September 2021:

1. "The Shawshank Redemption" (1994)
2. "The Godfather" (1972)
3. "The Godfather: Part II" (1974)
4. "The Dark Knight" (2008)
5. "Pulp Fiction" (1994)
6. "Schindler's List" (1993)`,
      timestamp: new Date(),
    },
  ])
  const [inputText, setInputText] = useState("")
  const scrollViewRef = useRef<ScrollView>(null)

  useEffect(() => {
    scrollViewRef.current?.scrollToEnd({ animated: true })
  }, [messages])

  const handleSendMessage = () => {
    if (inputText.trim() === "") return
    const newMessage: Message = {
      id: Date.now().toString(),
      type: "user",
      content: inputText,
      timestamp: new Date(),
    }
    setMessages([...messages, newMessage])
    setInputText("")

    setTimeout(() => {
      const aiResponse: Message = {
        id: (Date.now() + 1).toString(),
        type: "ai",
        content: "This is a sample AI response. In a real implementation, this would be generated by an AI model.",
        timestamp: new Date(),
      }
      setMessages((prev) => [...prev, aiResponse])
    }, 500)
  }

  const handleCopyMessage = (content: string) => {
    console.log("[v0] Copied message:", content)
  }

  const handleShareMessage = (content: string) => {
    console.log("[v0] Sharing message:", content)
  }

  const handleRegenerateResponse = () => {
    const lastMessageIndex = messages.length - 1
    if (messages[lastMessageIndex]?.type === "ai") {
      setMessages((prev) => prev.slice(0, -1))
      setTimeout(() => {
        const aiResponse: Message = {
          id: (Date.now() + 1).toString(),
          type: "ai",
          content: "This is a regenerated AI response with different content.",
          timestamp: new Date(),
        }
        setMessages((prev) => [...prev, aiResponse])
      }, 500)
    }
  }

  return (
    <SafeAreaProvider style={{ flex: 1, backgroundColor: "#f5f5f5" }}>
      {/* Header */}
      <View
        style={{
          flexDirection: "row",
          alignItems: "center",
          paddingHorizontal: 16,
          paddingVertical: 12,
          backgroundColor: "#ffffff",
          borderBottomWidth: 1,
          borderBottomColor: "#e5e5e5",
        }}
      >
        <Pressable onPress={() => router.back()} style={{ padding: 8 }}>
          <Text style={{ fontSize: 24, color: "#333" }}>←</Text>
        </Pressable>
        <Text style={{ fontSize: 18, fontWeight: "600", color: "#333", flex: 1, textAlign: "center" }}>
          AI Chat Assistant
        </Text>
        <View style={{ width: 40 }} />
      </View>

      {/* Chat */}
      <KeyboardAvoidingView
        behavior={Platform.OS === "ios" ? "padding" : "height"}
        style={{ flex: 1 }}
      >
        <ScrollView
          ref={scrollViewRef}
          style={{ flex: 1 }}
          contentContainerStyle={{ paddingHorizontal: 12, paddingVertical: 16 }}
        >
          {messages.map((message) => (
            <View key={message.id} style={{ marginBottom: 16 }}>
              {message.type === "user" ? (
                <View style={{ flexDirection: "row", alignItems: "flex-start", marginBottom: 8 }}>
                  <Image
                    source={aiChatAssistant.women}
                    style={{ width: 40, height: 40, borderRadius: 20, marginRight: 12 }}
                  />
                  <View
                    style={{
                      flex: 1,
                      backgroundColor: "#e8f0f7",
                      borderRadius: 12,
                      padding: 12,
                      flexDirection: "row",
                      alignItems: "center",
                    }}
                  >
                    <Text style={{ fontSize: 14, color: "#333", lineHeight: 20, flex: 1 }}>
                      {message.content}
                    </Text>
                    <Pressable onPress={() => handleCopyMessage(message.content)} style={{ marginLeft: 8, padding: 4 }}>
                      <Image source={aiChatAssistant.copy} style={{ width: 20, height: 20 }} />
                    </Pressable>
                  </View>
                </View>
              ) : (
                <View style={{ flexDirection: "row", alignItems: "flex-start", marginBottom: 8 }}>
                  <Image
                    source={aiChatAssistant.aiMagic}
                    style={{ width: 20, height: 20, marginRight: 12, marginTop: 4 }}
                  />
                  <View
                    style={{
                      flex: 1,
                      backgroundColor: "#f0e8f8",
                      borderRadius: 12,
                      padding: 12,
                    }}
                  >
                    <Text style={{ fontSize: 14, color: "#333", lineHeight: 20 }}>{message.content}</Text>
                    <View style={{ flexDirection: "row", marginTop: 8, justifyContent: "flex-start", gap: 8 }}>
                      <Pressable onPress={() => handleCopyMessage(message.content)} style={{ padding: 4 }}>
                        <Image source={aiChatAssistant.copy} style={{ width: 18, height: 18 }} />
                      </Pressable>
                      <Pressable onPress={() => handleShareMessage(message.content)} style={{ padding: 4 }}>
                        <Image source={aiChatAssistant.solarShareLinear} style={{ width: 18, height: 18 }} />
                      </Pressable>
                    </View>
                  </View>
                </View>
              )}
            </View>
          ))}
        </ScrollView>

        {/* Regenerate */}
        <View style={{ paddingHorizontal: 12, paddingVertical: 8 }}>
          <Pressable
            onPress={handleRegenerateResponse}
            style={{
              flexDirection: "row",
              alignItems: "center",
              justifyContent: "center",
              paddingVertical: 10,
              paddingHorizontal: 16,
              backgroundColor: "#ffffff",
              borderRadius: 8,
              borderWidth: 1,
              borderColor: "#ddd",
              gap: 8,
            }}
          >
            <Image source={aiChatAssistant.codeCompare} style={{ width: 16, height: 16 }} />
            <Text style={{ fontSize: 14, color: "#666", fontWeight: "500" }}>Regenerate Response</Text>
          </Pressable>
        </View>

        {/* Input */}
        <View
          style={{
            flexDirection: "row",
            alignItems: "flex-end",
            paddingHorizontal: 12,
            paddingVertical: 12,
            backgroundColor: "#ffffff",
            borderTopWidth: 1,
            borderTopColor: "#e5e5e5",
            gap: 8,
          }}
        >
          <TextInput
            style={{
              flex: 1,
              backgroundColor: "#f5f5f5",
              borderRadius: 20,
              paddingHorizontal: 16,
              paddingVertical: 10,
              fontSize: 14,
              color: "#333",
              maxHeight: 100,
            }}
            placeholder="Send a message"
            placeholderTextColor="#bbb"
            value={inputText}
            onChangeText={setInputText}
            multiline
            maxLength={500}
          />
          <Pressable onPress={handleSendMessage} style={{ paddingHorizontal: 12, paddingVertical: 10 }}>
            <Image source={aiChatAssistant.vector} style={{ width: 20, height: 20 }} />
          </Pressable>
        </View>
      </KeyboardAvoidingView>
    </SafeAreaProvider>
  )
}
